kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-rolebind
  namespace: default
subjects:
- kind: User
  name: user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io
